name: rdf_semantic_snowflake
channels:
  - https://repo.anaconda.com/pkgs/snowflake/
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - snowflake-snowpark-python
  - numpy
  - pandas
  - ipykernel
  - jupyter
  - matplotlib
  - seaborn
  - keyring
  - pip:
    - "snowflake-connector-python[secure-local-storage]"
    - requests
    - pyyaml